### ISSUE TITLE
Piston with two heads.

### ISSUE THREAD

**Issue by Psithief** [DonBruce64/BackInSlime#1]
### Versions
* Back in Slime-1.7.10-3.1.1
* Minecraft Forge 10.13.4.1558
* A whole bunch of unrelated mods

### Reproduction steps
1. Place two redstone blocks on top of each other.
2. Place a sticky piston from this mod on the side of the top redstone block.

![2016-01-28_16 20 36](https://cloud.githubusercontent.com/assets/1124846/12638836/1b721e62-c5db-11e5-940c-5ea92053b292.png)

It's a bit weird but I don't know how much it will annoy anyone.

**Comment by Psithief** [comment]
This actually happens in a lot more cases but I think this is the simplest example.

**Comment by DonBruce64** [comment]
Issue is fixed in version 3.1.2.  For some reason overriding a method and using the exact same calls doesn't work the same..?  Minecraft is weird.
