### ISSUE TITLE
Blocks get deleted if pushed to top of world.

### ISSUE THREAD

**Issue by Psithief** [DonBruce64/BackInSlime#2]
![2016-02-05_02 38 45](https://cloud.githubusercontent.com/assets/1124846/12825538/c55b4f94-cbb1-11e5-81a7-c91b462d021e.png)

I made machine that just moves itself straight up to the top of the world. The two blocks being pushed and the piston head were deleted when pushed over the limit, and the top two remaining blocks are at y=255.

I think the normal Minecraft behaviour is to prevent pistons from pushing in these circumstances.

**Comment by DonBruce64** [comment]
Fixed in version 3.1.6.
